---
driver:
  name: docker 
  socket: <%= ENV['DOCKER_HOST'] %>
driver_config:
  require_chef_omnibus: true
busser:
  sudo: true

platforms:
  - name: centos-6.4
    driver_config:
      image: ryuzee/centos_chef:6.4
  - name: ubuntu-12.04
    driver_config:
      image: ryuzee/ubuntu_chef:12.04

suites:
- name: default
  run_list: 
    - "recipe[apache2-simple::default]"
  attributes: {}
